server:
  port: 10001
spring:
  application:
    name: roubao-registry-eureka
  security:
    user:
      name: admin
      password: admin123
##################################################################################################
## Eureka服务端配置
##################################################################################################
eureka:
  instance:
    hostname: 127.0.0.1
    #表示eureka server收到client的心跳时间开始 到等待下一次时心跳时间的最大等待时间 默认为90s 超过等待90秒 eureka server就会该实例剔除服务注册中心 （按需更改，可以不配置使用默认）
    lease-expiration-duration-in-seconds: 90
    #标识eureka client发送给server端的频率 如果在规定时间内 server端还未接收到心跳 则剔除该实例 默认时间30s （按需更改，可以不配置使用默认）
    lease-renewal-interval-in-seconds: 30
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin123@${eureka.instance.hostname}:${server.port}/eureka
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/